### ISSUE TITLE
Adding header using set_header() not working

### ISSUE THREAD

**Issue by InTEGr8or** [spietika/restson-rust#33]
I noticed that the word "header" is mentioned nowhere on the README page, but there is a set_header() in [restson-rust/src/blocking.rs:47](https://github.com/spietika/restson-rust/blob/adffad56e3b086fc0736ff5a3f9b19d957c610bf/src/blocking.rs#L47)

When I attempt:
```
    let mut client = RestClient::builder()
        .blocking(&url).set_header("zsessionid", zsessionid).unwrap();
```

I get 
```
12 |         .blocking(&url).set_header("zsessionid", zsessionid).unwrap();
   |                         ^^^^^^^^^^ method not found in `Result<restson::blocking::RestClient, restson::Error>`
```

Are headers not-yet-implemented? I would like to troubleshoot this myself but I am not yet competent enough at Rust and am still working on executing my first successful header-containing HTTP request full-loop with strongly-typed result.

Are headers on the road-map?

**Comment by spietika** [comment]
Looking at the code snippet, the problem seems to be that `.set_header()` is called for the `Result` of the builder and not for the actual client object.

Basically the builder returns `Result<blocking::RestClient, Error>` which can contain the client or an error code if the creation failed. This has to be first unwrapped to get the client object. 

So in short, if you change the code as follows it should work:
```rust
let mut client = RestClient::builder().blocking(&url).unwrap();
client.set_header("zsessionid", zsessionid).unwrap();
```

Moreover, `.set_header()` does not return the REST client object so calling it in the `let mut` statement will actually assign the result of that operation in the `client` variable (and not the client object).

Keep in mind that `.unwrap()` will panic on error and exit the program. So you might eventually want to handle the error cases properly as well.

Hopefully this helps to solve the issue!

Here is a test case for reference (other test cases are good references for the different features as well):
https://github.com/spietika/restson-rust/blob/master/tests/headers.rs#L28
