### ISSUE TITLE
Make requests not use &mut reference

### ISSUE THREAD

**Issue by xfbs** [spietika/restson-rust#35]
Needing a mutable reference means that only one request can be made at a time (?). Should that be fixed?

**Comment by spietika** [comment]
This would be a good improvement indeed. The original implementation of restson did not have async support so this was not really an issue then (all the requests were blocking). But now with async this is quite a big limitation.

In the current implementation, capturing the response headers would not work without mut. Though, that would have to be refactored anyway to work correctly with multiple concurrent requests.

**Comment by spietika** [comment]
There is now a version that does not need mut client in the const-client branch: https://github.com/spietika/restson-rust/tree/const-client
@Tuetuopay had already implemented this feature in his fork, and the relevant commits were cherry-picked from there with minor changes (e.g. handling for lib-simd-json added).

Test case making concurrent requests: https://github.com/spietika/restson-rust/blob/const-client/tests/get_async.rs#L78

This version is not yet published to crates.io since it still needs some minor additional work. E.g. updating the readme.

**Comment by Tuetuopay** [comment]
Oohh thanks for reminding me I've forgotten to upstream this branch for ages :smile: 

FWIW I've been using this branch in production, well, since making it. So I can vouch for it working (ignoring the fact  wrote it).

**Comment by spietika** [comment]
Good to hear that the crate has been useful in your project! The implementation is solid and the tests are green, so I am happy to take these changes in. I will make some updates to the readme and then push a new version to crates.io.

**Comment by spietika** [comment]
Published in v1.2.0
